packages:
  - apps/*
  - packages/*

catalog:
  eslint: ^9
  hono: ^4.12.8
  "@hono/node-server": ^1.19.10
  lodash: ">=4.17.23"

# overrides:
#   hono: ^4.12.8
#   "@hono/node-server": ^1.19.10
#   lodash: ">=4.17.23"

ignoredBuiltDependencies:
  - bcrypt
